export { default as Hero } from "./Hero";
export { default as Categories } from "./Categories";
export { default as CategoryItem } from "./CategoryItem";
export { default as About } from "./About";
export { default as Products } from "./Products";
export { default as Brands } from "./Brands";
export { default as News } from "./News";
export { default as Contacts } from "./Contacts";
export { default as SEO } from "./SEO";
